# Generated by Django 3.0.4 on 2021-06-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_auto_20210610_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.Client'),
        ),
    ]
