# Generated by Django 3.0.4 on 2021-06-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_auto_20210610_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_date',
            new_name='date_created',
        ),
    ]
