# Generated by Django 3.0.4 on 2021-06-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20210615_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
