# Generated by Django 3.0.4 on 2021-06-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_invoice_invoice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('receiving_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('receiving_amount', models.IntegerField()),
                ('receiving_details', models.CharField(max_length=255, null=True)),
                ('receiving_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
    ]
