# Generated by Django 3.0.4 on 2021-06-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0008_receiving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving',
            old_name='receiving_details',
            new_name='receiving_description',
        ),
    ]
