# Generated by Django 3.0.4 on 2021-07-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_auto_20210712_0556'),
        ('Clients', '0009_auto_20210615_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_qty', models.IntegerField()),
                ('entry_rate', models.IntegerField()),
                ('entry_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Invoice')),
                ('entry_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.Service')),
            ],
        ),
    ]
