# Generated by Django 3.0.4 on 2021-07-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_invoice_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_amount',
        ),
    ]
