# Generated by Django 3.0.4 on 2021-07-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_remove_invoice_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
