# Generated by Django 3.0.4 on 2021-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('recurring_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurring_name', models.CharField(max_length=255)),
                ('recurring_price', models.IntegerField()),
                ('recurring_frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('service_price', models.IntegerField()),
            ],
        ),
    ]
