# Generated by Django 3.0.4 on 2021-07-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_default_qty',
            field=models.IntegerField(default=1),
        ),
    ]
