# Generated by Django 3.0.4 on 2021-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_amount', models.IntegerField()),
                ('expense_type', models.CharField(choices=[('Marketing', 'Marketing'), ('Payroll', 'Payroll')], max_length=255)),
                ('expense_date', models.DateField()),
            ],
        ),
    ]
