# Generated by Django 3.0.4 on 2021-07-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_date',
            new_name='date_created',
        ),
    ]
