# Generated by Django 3.0.4 on 2021-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_auto_20210711_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(max_length=255),
        ),
    ]
