# Generated by Django 3.2.16 on 2022-12-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('department_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('medicines_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicines_qty', models.IntegerField()),
                ('medicines_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentBooking.appointment')),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentBooking.medicines')),
            ],
        ),
    ]
