# Generated by Django 3.2.16 on 2022-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('demo_id', models.AutoField(primary_key=True, serialize=False)),
                ('demo_desc', models.CharField(max_length=255)),
            ],
        ),
    ]
