# Generated by Django 3.2.16 on 2022-12-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0005_auto_20221208_0934'),
        ('AppointmentBooking', '0003_auto_20221223_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSystem.doctor'),
        ),
    ]
