# Generated by Django 3.2.16 on 2022-12-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0005_appointment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
