# Generated by Django 3.2.16 on 2022-12-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0008_auto_20221224_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
