# Generated by Django 3.2.16 on 2023-03-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0006_alter_doctor_user'),
        ('AppointmentBooking', '0010_auto_20221224_0312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='UserSystem.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='UserSystem.patient'),
        ),
        migrations.DeleteModel(
            name='Medicines',
        ),
    ]
