# Generated by Django 3.2.18 on 2023-03-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0011_auto_20230326_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
