# Generated by Django 3.2.16 on 2023-03-31 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0012_delete_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppointmentBooking.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
