# Generated by Django 3.2.16 on 2023-04-02 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0013_auto_20230331_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
