# Generated by Django 3.2.16 on 2023-04-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0006_alter_doctor_user'),
        ('AppointmentBooking', '0014_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserSystem.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentBooking.appointment'),
        ),
    ]
