# Generated by Django 3.2.16 on 2023-04-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0006_alter_doctor_user'),
        ('AppointmentBooking', '0015_auto_20230402_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserSystem.doctor'),
        ),
    ]
