# Generated by Django 3.0.4 on 2021-06-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('receiving_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiving_date', models.DateField()),
                ('receiving_amount', models.IntegerField()),
                ('receiving_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
    ]
