# Generated by Django 3.0.4 on 2021-06-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receivings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving',
            old_name='receiving_date',
            new_name='date_created',
        ),
    ]
