# Generated by Django 3.0.4 on 2021-06-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receivings', '0003_receiving_receiving_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiving',
        ),
    ]
