# Generated by Django 3.0.4 on 2021-06-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_description', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField()),
                ('payment_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_vendor', to='Vendors.Vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_description', models.CharField(max_length=255)),
                ('bill_amount', models.IntegerField()),
                ('bill_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_vendor', to='Vendors.Vendors')),
            ],
        ),
    ]
