# Generated by Django 3.0.4 on 2021-06-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0004_auto_20210611_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='bill_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_date',
            new_name='date_created',
        ),
    ]
