# Generated by Django 3.0.4 on 2021-06-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0005_auto_20210611_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vendor_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
