# Generated by Django 3.0.4 on 2021-07-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0006_auto_20210615_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='id',
        ),
        migrations.AddField(
            model_name='bills',
            name='bill_id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
